spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    gateway:
      routes:
        - id: books


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
